fetchData: 
	mkdir TrainingDS TestingDS
	curl https://www.kaggle.com/c/digit-recognizer/download/train.csv -o ./TrainingDS/train.csv
	curl https://www.kaggle.com/c/digit-recognizer/download/test.csv -o ./TestingDS/test.csv
